name: Sync Fork (preserve workflows & update.cmd)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/robotze/GithubDesktopZhTool.git
          git fetch upstream

      - name: Sync with upstream (preserve workflows & update.cmd)
        run: |
          mkdir -p tmp_backup/.github/workflows
          cp -r .github/workflows/* tmp_backup/.github/workflows/ 2>/dev/null || true
          cp update.cmd tmp_backup/ 2>/dev/null || true

          git checkout main
          git reset --hard upstream/main

          mkdir -p .github/workflows
          cp -r tmp_backup/.github/workflows/* .github/workflows/ 2>/dev/null || true
          cp tmp_backup/update.cmd ./ 2>/dev/null || true

          rm -rf tmp_backup

          git add .
          git commit -m "Auto-sync from upstream (preserving workflows & update.cmd)" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main --force
